env: "production"

server:
  host: "localhost"
  port: ":8080"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "1106"
  dbname: "pet_project"
  sslmode: "disable"

redis:
  address: "localhost:6379"